spring.datasource.url = ${rules_engine_url:jdbc:postgresql://localhost:5432/rules-engine}
spring.datasource.username = ${rules_engine_username}
spring.datasource.password = ${rules_engine_password}
server.port=9004

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
#create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect